-- DATE ¿¿¿¿ ¿¿¿¿ hh:mm:ss ¿¿
ALTER TABLE tbBaseInterestRate
MODIFY COLUMN date DATE;

-- ¿¿¿ ¿¿ ¿ ¿¿ ¿¿
ALTER TABLE tbBaseInterestRate
CHANGE COLUMN base_interest_rate BaseInterestRate VARCHAR(5);

-- ¿¿¿ ¿¿
ALTER TABLE tbAPTPrice
CHANGE COLUMN `¿¿¿¿(¿¿)` ¿¿¿¿_¿¿ VARCHAR(2000);

ALTER TABLE tbAPTPrice
CHANGE COLUMN `¿¿¿¿(¿)` ¿¿¿¿_m2 VARCHAR(2000);

ALTER TABLE tbAPTPrice
CHANGE COLUMN `¿¿¿¿(¿)` ¿¿¿¿_m2 VARCHAR(2000);

ALTER TABLE tbAPTPrice
CHANGE COLUMN `¿¿¿ ¿¿¿¿¿¿¿ ¿¿¿¿` ¿¿_¿¿¿¿¿_¿¿ VARCHAR(2000);


-- ¿¿ ¿¿ ¿¿
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿ CHAR(4);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿¿ VARCHAR(10);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿ NVARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿¿ VARCHAR(10);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿ NVARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿ VARCHAR(5);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿¿ VARCHAR(5);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿ VARCHAR(10);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿ VARCHAR(10);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿ VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿_¿¿ VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿_m2 VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿ VARCHAR(10);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿ VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿ DATE;
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿ CHAR(4);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿ VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿¿¿ VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN ¿¿_¿¿¿¿¿_¿¿ VARCHAR(2000);

-- ¿¿¿_DATE ¿¿ ¿¿
ALTER TABLE tbAPTPrice ADD COLUMN ¿¿¿_DATE DATE;
ALTER TABLE tbAPTPrice modify COLUMN ¿¿¿_DATE VARCHAR(10);

-- BIGINT ¿¿¿¿ ¿¿¿ ¿¿¿¿¿ ¿
SET SQL_SAFE_UPDATES = 0;

UPDATE tbAPTPrice
SET ¿¿¿_DATE = CAST(CAST(¿¿¿ AS UNSIGNED) AS DATE);

SET SQL_SAFE_UPDATES = 1;

-- ¿¿ ¿¿ ¿¿
ALTER TABLE tbAPTPrice DROP COLUMN ¿¿¿;

-- ¿¿¿ ¿¿
SELECT ¿¿¿_DATE FROM tbAPTPrice LIMIT 10;

-- idx ¿¿ ¿¿
ALTER TABLE tbAPTPrice ADD COLUMN idx int AUTO_INCREMENT PRIMARY KEY;


-- ¿¿¿ ¿¿ ¿¿¿ ¿¿
CREATE TABLE lg_prediction (
    lg_idx INT AUTO_INCREMENT PRIMARY KEY,
    idx INT NOT NULL,
    prediction VARCHAR(10000),
    getdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idx) REFERENCES tbAPTPrice(idx)
);

ALTER TABLE lg_prediction
MODIFY COLUMN prediction VARCHAR(10000) NOT NULL;
