-- DATE 타입으로 수정해서 hh:mm:ss 제거
ALTER TABLE tbBaseInterestRate
MODIFY COLUMN date DATE;

-- 컬럼명 수정 및 타입 변경
ALTER TABLE tbBaseInterestRate
CHANGE COLUMN base_interest_rate BaseInterestRate VARCHAR(5);

-- 컬럼명 수정
ALTER TABLE tbAPTPrice
CHANGE COLUMN `물건금액(만원)` 물건금액_만원 VARCHAR(2000);

ALTER TABLE tbAPTPrice
CHANGE COLUMN `건물면적(㎡)` 건물면적_m2 VARCHAR(2000);

ALTER TABLE tbAPTPrice
CHANGE COLUMN `토지면적(㎡)` 토지면적_m2 VARCHAR(2000);

ALTER TABLE tbAPTPrice
CHANGE COLUMN `신고한 개업공인중개사 시군구명` 신고_공인중개사_지역 VARCHAR(2000);


-- 컬럼 타입 수정
ALTER TABLE tbAPTPrice MODIFY COLUMN 접수연도 CHAR(4);
ALTER TABLE tbAPTPrice MODIFY COLUMN 자치구코드 VARCHAR(10);
ALTER TABLE tbAPTPrice MODIFY COLUMN 자치구명 NVARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN 법정동코드 VARCHAR(10);
ALTER TABLE tbAPTPrice MODIFY COLUMN 법정동명 NVARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN 지번구분 VARCHAR(5);
ALTER TABLE tbAPTPrice MODIFY COLUMN 지번구분명 VARCHAR(5);
ALTER TABLE tbAPTPrice MODIFY COLUMN 본번 VARCHAR(10);
ALTER TABLE tbAPTPrice MODIFY COLUMN 부번 VARCHAR(10);
ALTER TABLE tbAPTPrice MODIFY COLUMN 건물명 VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN 물건금액_만원 VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN 건물면적_m2 VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN 층 VARCHAR(10);
ALTER TABLE tbAPTPrice MODIFY COLUMN 권리구분 VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN 취소일 DATE;
ALTER TABLE tbAPTPrice MODIFY COLUMN 건축년도 CHAR(4);
ALTER TABLE tbAPTPrice MODIFY COLUMN 건물용도 VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN 신고구분 VARCHAR(2000);
ALTER TABLE tbAPTPrice MODIFY COLUMN 신고_공인중개사_지역 VARCHAR(2000);

-- 계약일_DATE 컬럼 추가
ALTER TABLE tbAPTPrice ADD COLUMN 계약일_DATE DATE;
ALTER TABLE tbAPTPrice modify COLUMN 계약일_DATE VARCHAR(10);

-- BIGINT 다녀오면 소수점 제거된다고 함
SET SQL_SAFE_UPDATES = 0;

UPDATE tbAPTPrice
SET 계약일_DATE = CAST(CAST(계약일 AS UNSIGNED) AS DATE);

SET SQL_SAFE_UPDATES = 1;

-- 기존 컬럼 제거
ALTER TABLE tbAPTPrice DROP COLUMN 계약일;

-- 데이터 확인
SELECT 계약일_DATE FROM tbAPTPrice LIMIT 10;

-- idx 컬럼 추가
ALTER TABLE tbAPTPrice ADD COLUMN idx int AUTO_INCREMENT PRIMARY KEY;


-- 예측값 로그 테이블 추가
CREATE TABLE lg_prediction (
    lg_idx INT AUTO_INCREMENT PRIMARY KEY,
    idx INT NOT NULL,
    prediction VARCHAR(10000),
    getdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idx) REFERENCES tbAPTPrice(idx)
);

ALTER TABLE lg_prediction
MODIFY COLUMN prediction VARCHAR(10000) NOT NULL;


